export enum ApiUrl {
  GetInput = 'get-input',
  PostInput = 'post-input',
  DeleteInput = 'delete-input',
  GetBookingLayout = 'get-booking-layout',
  GetBookingLayoutById = 'get-booking-layout-by-id',
  PostBookingLayout = 'post-booking-layout',
  DeleteInputFromBookingLayout = 'delete-input-from-booking-layout',
  DeleteBookingLayout = 'delete-booking-layout',
  PatchBookingLayout = 'patch-booking-layout',
  Login = 'login',
  Register = 'register',
  GetUser = 'get-user',
  GetBookingLayoutUser = 'get-booking-layout-user',
}
